### ISSUE TITLE
Possible to update timer interval after initialization?

### ISSUE THREAD

**Issue by brylie** [inf0rmatix/reliable_interval_timer#5]
I have a [metronome app](https://github.com/AlchemicalExperiences/Khronos) that uses this package for accurate timing of the metronome sound. The app lets users change the tempo of the metronome. When they do, there is some noticeable lag where the tone stops sounding while a new ReliableIntervalTimer instance loads. Rather than creating a new instance, is it possible to update the interval on the existing instance so there is less time spent creating a new instance and isolate?

**Comment by inf0rmatix** [comment]
Hi @brylie!

I am currently super busy, so it would come down to you to create a PR :)
Technically, it should be possible to change to interval by passing the new duration to the isolate instance.
